version: "3.4"

services:
  backend:
    container_name: backend
    image: phamminhduy/htqldtkh-backend
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network