version: "3.4"

services:
  app:
    image: htqldtkh-backend
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
  
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: htqldtkh_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: htqldtkh_cse
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./docker/data/mongoDb:/data/db
    restart: unless-stopped
    networks:
      - mongo-compose-network
    command: --auth
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: htqldtkh_cse

    depends_on:
      - mongodb
    networks:
      - mongo-compose-network

  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   container_name: swagger_ui_container
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./doc:/usr/share/nginx/html/doc
  #   environment:
  #     API_URL: doc/openapi.yamlnetworks:
networks:
  mongo-compose-network:
    driver: bridge