###
POST http://localhost:8000/api/auth/test
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2luaCB2acOqbiIsIl9pZCI6IjYzYjYzYzM3OWRkMDE0NjdjNGYwOTUwYSIsInN0dWRlbnRJZCI6IjE5MTI5MTYiLCJlbWFpbCI6Im1kdXlAZ21haWwuY29tIiwiaWF0IjoxNjcyODg4OTUyLCJleHAiOjE2NzI4OTYxNTJ9.BJI3Jrd33UtJJASgxcBhHW34QyBmCn9Duc5z245BRFU